@protocol=http://
@host=localhost
@port=:5000
@prefix=/v1
@baseUrl={{protocol}}{{host}}{{port}}{{prefix}}

### Test get users
GET {{baseUrl}}/users HTTP/1.1

### Test get announces
GET {{baseUrl}}/announces HTTP/1.1



### Test create user
POST {{baseUrl}}/users HTTP/1.1
content-type: application/json

{
    "nickname": "vincent",
    "mail": "vincent@tata.fr",
    "password": "qwerty",
    "city": "Totocity",
    "picture": "http://mypicture",
    "isAdmin": "true"
}


### Test create announce
POST {{baseUrl}}/announces HTTP/1.1
content-type: application/json

{
    "title": "cactus de myriam",
    "image": "https://images.de.cactus",
    "description": "C'est le cactus de vincent.",
    "category": "Donnation",
    "visitor_id": "2"
}


### Test login
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
    "nickname": "vincent",
    "mail": "vincent@tata.fr",
    "password": "qwerty",
    "city": "Totocity",
    "picture": "http://mypicture",
    "isAdmin": "true"
}


### Update user
POST {{baseUrl}}/users/1 HTTP/1.1
content-type: application/json

{
    "nickname": "tata",
    "mail": "tutu@tata.fr",
    "password": "123415",
    "city": "Tutucity",
    "picture": "http://mypicture2",
    "isAdmin": "false"
}


### Update announce
POST {{baseUrl}}/announces/2 HTTP/1.1
content-type: application/json

{
    "title": "Ibiscus de myriam",
    "image": "https://images.de.cactus",
    "description": "C'est la demande de vincent. ",
    "category": "Demande",
    "visitor_id": "2"
}


### Delete user
DELETE {{baseUrl}}/users/2 HTTP/1.1
content-type: application/json


### Delete announce
DELETE {{baseUrl}}/announces/2 HTTP/1.1
content-type: application/json
