@protocol=http://
@host=localhost
@port=:5000
@prefix=/v1
@baseUrl={{protocol}}{{host}}{{port}}{{prefix}}

### Test get users
GET {{baseUrl}}/users/3 HTTP/1.1

### Test get announces
GET {{baseUrl}}/announces HTTP/1.1



### Test create user
POST {{baseUrl}}/users HTTP/1.1
content-type: application/json

{
    "nickname": "vincent",
    "mail": "vincent@oclock.io",
    "password": "qwerty",
    "city": "Paris",
    "picture": "https://media-exp1.licdn.com/dms/image/D4E35AQES9YjdYcnlYQ/profile-framedphoto-shrink_400_400/0/1642097948572?e=1643112000&v=beta&t=qSnlLfHnqkiWvlY1Dc8XgHHPFJTdbtrGT6iFhjTli5A",
    "isAdmin": "true"
}


### Test create announce
POST https://shokubutsu.herokuapp.com/v1/announces HTTP/1.1
content-type: application/json

{
    "title": "cactus de myriam",
    "image": "https://images.de.cactus",
    "description": "C'est le cactus de vincent.",
    "category": "Donnation",
    "visitor_id": "1"
}


### Test login
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
    "mail": "vincent@oclock.io",
    "password": "qwerty"
}

### Test reconnect with token
GET {{baseUrl}}/login/reconnect HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjozLCJpYXQiOjE2NDMwMzY5OTIsImV4cCI6MTY0MzEyMzM5Mn0.JW6Yk04UdaffKAyRhqE_OhyTjACYG10KkIq59E3bCuk



### Update user
POST {{baseUrl}}/users/1 HTTP/1.1
content-type: application/json

{
    "mail": "tutu@tata.fr",
    "password": "123415",
    "city": "Tutucity",
    "picture": "http://mypicture2",
    "isAdmin": "false"
}


### Update announce
POST {{baseUrl}}/announces/2 HTTP/1.1
content-type: application/json

{
    "title": "Ibiscus de myriam",
    "image": "https://images.de.cactus",
    "description": "C'est la demande de vincent. ",
    "category": "Demande",
    "visitor_id": "2"
}


### Delete user
DELETE {{baseUrl}}/users/2 HTTP/1.1
content-type: application/json


### Delete announce
DELETE https://shokubutsu.herokuapp.com/v1/announces/1 HTTP/1.1
content-type: application/json


