@protocol=http://
@host=localhost
@port=:5000
@prefix=/v1
@baseUrl={{protocol}}{{host}}{{port}}{{prefix}}

### Test get users
GET {{baseUrl}}/users HTTP/1.1



### Test create
POST {{baseUrl}}/users HTTP/1.1
content-type: application/json

{
    "nickname": "carotte",
    "mail": "carotte@tata.fr",
    "password": "qwerty",
    "city": "Totocity",
    "isAdmin": "true"
}


### Test login
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
    "nickname": "carotte",
    "mail": "carotte@tata.fr",
    "password": "qwerty",
    "city": "Totocity",
    "isAdmin": "true"
}

