@protocol=http://
@host=localhost
@port=:5000
@prefix=/v1
@baseUrl={{protocol}}{{host}}{{port}}{{prefix}}

### Test get bookmarks
GET {{baseUrl}}/bookmarks/6 HTTP/1.1

### Test post bookmarks
POST {{baseUrl}}/bookmarks/1/2 HTTP/1.1
content-type: application/json

### Test delete bookmarks
DELETE {{baseUrl}}/bookmarks/1/1 HTTP/1.1
content-type: application/json