@protocol=http://
@host=localhost
@port=:5000
@prefix=/v1
@baseUrl={{protocol}}{{host}}{{port}}{{prefix}}

### Test get users
GET https://shokubutsu.herokuapp.com/v1/users HTTP/1.1


### Test create user
POST {{baseUrl}}/users HTTP/1.1
content-type: application/json

{
    "nickname": "Toto",
    "mail": "non@non.fr",
    "password": "asdqwe123",
    "city": "Paris",
    "picture": "https://mypicture"
}



### Test login
POST https://shokubutsu.herokuapp.com/v1/login HTTP/1.1
content-type: application/json

{
    "mail": "myriam123@myriam.com",
    "password" : "Myriam123"
}


### Test CheckPWD
POST {{baseUrl}}/users/2 HTTP/1.1
content-type: application/json

{
    "id":2,
    "password": "asdqwe123"
}

### Test reconnect with token
GET {{baseUrl}}/login/reconnect HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjozLCJpYXQiOjE2NDMwMzc3NzAsImV4cCI6MTY0MzEyNDE3MH0.6YwFETAGxDiEZOXOCvQtBuQp0CthgoDzSXIHEJ1Cs04



### Update user
PATCH https://shokubutsu.herokuapp.com/v1/users/3 HTTP/1.1
content-type: application/json

{
    "nickname": "toto",
    "mail": "toto@oclock.io",
    "password": "asdqwe123",
    "city": "Paris",
    "picture": "https://mypicture"
}


### Delete user
DELETE https://shokubutsu.herokuapp.com/v1/users/2 HTTP/1.1
content-type: application/json


### Delete image

DELETE https://shokubutsu.herokuapp.com/v1/delete-image/ HTTP/1.1
content-type: application/json

{
    "image_url": "https://res.cloudinary.com/shokubutsu/image/upload/v1643367444/kwkgbk417iftmmt9t90h.jpg"
}

### update image user
PATCH {{baseUrl}}/update-image HTTP/1.1
Content-Type: application/json

{   
    "userId": 2,
    "image_url": "NULL"
}