@protocol=http://
@host=localhost
@port=:5000
@prefix=/v1
@baseUrl={{protocol}}{{host}}{{port}}{{prefix}}

### Test get users
GET https://shokubutsu.herokuapp.com/v1/users/ HTTP/1.1


### Test create user
POST {{baseUrl}}/users HTTP/1.1
content-type: application/json

{
    "nickname": "Patrice",
    "mail": "Patrice@oclock.io",
    "password": "12345",
    "city": "Paris",
    "picture": "https://res.cloudinary.com/shokubutsu/image/upload/v1643361653/upload/pmxxrskovl8c2s6fbt7s.jpg"
}



### Test login
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
    "nickname": "vincent",
    "mail": "vincent2@oclock.io",
    "password": "qwerty",
    "city": "Paris",
    "picture": "https://media-exp1.licdn.com/dms/image/D4E35AQES9YjdYcnlYQ/profile-framedphoto-shrink_400_400/0/1642097948572?e=1643112000&v=beta&t=qSnlLfHnqkiWvlY1Dc8XgHHPFJTdbtrGT6iFhjTli5A",
    "isAdmin": "true"
}

### Test reconnect with token
GET {{baseUrl}}/login/reconnect HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjozLCJpYXQiOjE2NDMwMzc3NzAsImV4cCI6MTY0MzEyNDE3MH0.6YwFETAGxDiEZOXOCvQtBuQp0CthgoDzSXIHEJ1Cs04



### Update user
POST {{baseUrl}}/users/5 HTTP/1.1
content-type: application/json

{
    "nickname": "vincent",
    "mail": "blablablablabla",
    "password": "qwerty",
    "city": "Paris",
    "picture": "https://media-exp1.licdn.com/dms/image/D4E35AQES9YjdYcnlYQ/profile-framedphoto-shrink_400_400/0/1642097948572?e=1643112000&v=beta&t=qSnlLfHnqkiWvlY1Dc8XgHHPFJTdbtrGT6iFhjTli5A",
    "isAdmin": "true"
}


### Delete user
DELETE {{baseUrl}}/users/10 HTTP/1.1
content-type: application/json


### Delete image

DELETE {{baseUrl}}/delete-image/ HTTP/1.1
content-type: application/json

{
    "url": "https://res.cloudinary.com/shokubutsu/image/upload/v1643367357/ucejbvo7wq2clgb91cst.png"
}
